/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Process is up. Does not touch dependencies.
         */
        get: operations["liveness_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Dependencies are reachable; returns 503 if any check fails.
         */
        get: operations["readiness_api_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Scan
         * @description Start a scan. Returns at once; follow `events_url` for live progress, then read
         *     `result_url` for the report.
         */
        post: operations["create_scan_api_scans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scan
         * @description The scan's status and, once finished, its full report.
         */
        get: operations["get_scan_api_scans__scan_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Scan
         * @description Delete the scan and its uploaded files.
         */
        delete: operations["delete_scan_api_scans__scan_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scan Events
         * @description Server-Sent Events: a `progress` event on every stage change, then one `done` event.
         *
         *     Progress is read from MongoDB, so any API process can serve the stream.
         */
        get: operations["scan_events_api_scans__scan_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parse/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse Resume
         * @description Parse a resume: text, sections, contact details and the ATS format report.
         */
        post: operations["parse_resume_api_parse_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parse/job-description": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse Job Description
         * @description Parse a job description given as pasted `text` or an uploaded `file` (exactly one).
         */
        post: operations["parse_job_description_api_parse_job_description_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extract/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Resume Profile
         * @description Extract a structured profile: skills (normalized), roles, experience, education.
         */
        post: operations["extract_resume_profile_api_extract_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extract/job-description": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Job Requirements
         * @description Extract hiring requirements: must-have vs nice-to-have skills, years, seniority.
         */
        post: operations["extract_job_requirements_api_extract_job_description_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Score Resume
         * @description Score synchronously, without saving or suggestions. Use `POST /api/scans` in the app.
         */
        post: operations["score_resume_api_score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ATSScore */
        ATSScore: {
            /** Total */
            total: number;
            /**
             * Band
             * @enum {string}
             */
            band: "strong" | "good" | "weak";
            /** Components */
            components: components["schemas"]["ComponentScore"][];
            /** Skills */
            skills: components["schemas"]["SkillMatch"][];
            /** Responsibilities */
            responsibilities: components["schemas"]["ResponsibilityMatch"][];
            /** Scoring Version */
            scoring_version: string;
        };
        /** Body_create_scan_api_scans_post */
        Body_create_scan_api_scans_post: {
            /**
             * Resume
             * @description Resume: PDF, DOCX or TXT
             */
            resume: string;
            /** Jd Text */
            jd_text?: string | null;
            /**
             * Jd File
             * @description JD: PDF, DOCX or TXT
             */
            jd_file?: string | null;
        };
        /** Body_extract_job_requirements_api_extract_job_description_post */
        Body_extract_job_requirements_api_extract_job_description_post: {
            /** Text */
            text?: string | null;
            /**
             * File
             * @description PDF, DOCX or TXT
             */
            file?: string | null;
        };
        /** Body_extract_resume_profile_api_extract_resume_post */
        Body_extract_resume_profile_api_extract_resume_post: {
            /**
             * File
             * @description PDF, DOCX or TXT
             */
            file: string;
        };
        /** Body_parse_job_description_api_parse_job_description_post */
        Body_parse_job_description_api_parse_job_description_post: {
            /** Text */
            text?: string | null;
            /**
             * File
             * @description PDF, DOCX or TXT
             */
            file?: string | null;
        };
        /** Body_parse_resume_api_parse_resume_post */
        Body_parse_resume_api_parse_resume_post: {
            /**
             * File
             * @description PDF, DOCX or TXT
             */
            file: string;
        };
        /** Body_score_resume_api_score_post */
        Body_score_resume_api_score_post: {
            /**
             * Resume
             * @description Resume: PDF, DOCX or TXT
             */
            resume: string;
            /** Jd Text */
            jd_text?: string | null;
            /**
             * Jd File
             * @description JD: PDF, DOCX or TXT
             */
            jd_file?: string | null;
        };
        /** ComponentScore */
        ComponentScore: {
            /**
             * Name
             * @enum {string}
             */
            name: "keywords" | "semantic" | "experience" | "title" | "education" | "format";
            /** Score */
            score: number | null;
            /** Weight */
            weight: number;
            /** Summary */
            summary: string;
        };
        /** ContactInfo */
        ContactInfo: {
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Linkedin */
            linkedin?: string | null;
            /** Github */
            github?: string | null;
        };
        /** Education */
        Education: {
            /**
             * Degree
             * @description Degree as written, e.g. 'B.Tech', 'MSc'
             */
            degree?: string | null;
            /**
             * Field
             * @description Field of study, e.g. 'Computer Science'
             */
            field?: string | null;
            /** Institution */
            institution?: string | null;
            /** Graduation Year */
            graduation_year?: number | null;
            level: components["schemas"]["EducationLevel"];
        };
        /**
         * EducationLevel
         * @enum {string}
         */
        EducationLevel: "high_school" | "diploma" | "bachelor" | "master" | "phd" | "other";
        /**
         * FileKind
         * @enum {string}
         */
        FileKind: "pdf" | "docx" | "text";
        /** FileSummary */
        FileSummary: {
            /** Filename */
            filename: string | null;
            kind: components["schemas"]["FileKind"];
            /** Size Bytes */
            size_bytes: number;
        };
        /** FormatIssue */
        FormatIssue: {
            /** Code */
            code: string;
            severity: components["schemas"]["Severity"];
            /** Message */
            message: string;
            /** Suggestion */
            suggestion: string;
        };
        /** FormatReport */
        FormatReport: {
            /** Format Score */
            format_score: number;
            /** Parseable */
            parseable: boolean;
            /** Issues */
            issues: components["schemas"]["FormatIssue"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** App */
            app: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
        };
        /** JobDescriptionAnalysis */
        JobDescriptionAnalysis: {
            source: components["schemas"]["FileKind"];
            /** Word Count */
            word_count: number;
            /** Sections */
            sections: components["schemas"]["Section"][];
            /** Text */
            text: string;
        };
        /** JobDescriptionExtractResponse */
        JobDescriptionExtractResponse: {
            file: components["schemas"]["UploadInfo"] | null;
            requirements: components["schemas"]["JobRequirements"];
        };
        /** JobDescriptionParseResponse */
        JobDescriptionParseResponse: {
            file: components["schemas"]["UploadInfo"] | null;
            analysis: components["schemas"]["JobDescriptionAnalysis"];
        };
        /** JobRequirements */
        JobRequirements: {
            /** Title */
            title: string | null;
            seniority: components["schemas"]["Seniority"];
            /** Min Years Experience */
            min_years_experience: number | null;
            /** Must Have Skills */
            must_have_skills: components["schemas"]["SkillRequirement"][];
            /** Nice To Have Skills */
            nice_to_have_skills: components["schemas"]["SkillRequirement"][];
            /** Soft Skills */
            soft_skills: string[];
            education_level: components["schemas"]["EducationLevel"] | null;
            /** Education Fields */
            education_fields: string[];
            /** Responsibilities */
            responsibilities: string[];
        };
        /**
         * LayoutSignals
         * @description Layout facts gathered while parsing; consumed by the ATS format check.
         */
        LayoutSignals: {
            /** Page Count */
            page_count?: number | null;
            /**
             * Has Text Layer
             * @default true
             */
            has_text_layer: boolean;
            /**
             * Multi Column
             * @default false
             */
            multi_column: boolean;
            /**
             * Table Count
             * @default 0
             */
            table_count: number;
            /**
             * Image Count
             * @default 0
             */
            image_count: number;
            /**
             * Text Box Count
             * @default 0
             */
            text_box_count: number;
            /**
             * Header Footer Text
             * @default
             */
            header_footer_text: string;
        };
        /**
         * Priority
         * @enum {string}
         */
        Priority: "high" | "medium" | "low";
        /** ReadinessResponse */
        ReadinessResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
            /** Checks */
            checks: {
                [key: string]: boolean;
            };
        };
        /** ResponsibilityMatch */
        ResponsibilityMatch: {
            /** Responsibility */
            responsibility: string;
            /** Score */
            score: number;
            /** Best Evidence */
            best_evidence: string | null;
        };
        /**
         * ResumeAnalysis
         * @description Everything Phase 2 learns from a resume file.
         */
        ResumeAnalysis: {
            kind: components["schemas"]["FileKind"];
            /** Word Count */
            word_count: number;
            signals: components["schemas"]["LayoutSignals"];
            contact: components["schemas"]["ContactInfo"];
            /** Sections */
            sections: components["schemas"]["Section"][];
            /** Unrecognized Headings */
            unrecognized_headings: string[];
            format_report: components["schemas"]["FormatReport"];
            /** Text */
            text: string;
        };
        /** ResumeExtractResponse */
        ResumeExtractResponse: {
            file: components["schemas"]["UploadInfo"];
            profile: components["schemas"]["ResumeProfile"];
        };
        /** ResumeParseResponse */
        ResumeParseResponse: {
            file: components["schemas"]["UploadInfo"];
            analysis: components["schemas"]["ResumeAnalysis"];
        };
        /** ResumeProfile */
        ResumeProfile: {
            /** Current Title */
            current_title: string | null;
            /** Roles */
            roles: components["schemas"]["Role"][];
            /**
             * Experience Years
             * @description Computed from role dates (internships excluded); falls back to the stated years when roles have no dates
             */
            experience_years: number | null;
            /** Internship Months */
            internship_months: number;
            /** Skills */
            skills: string[];
            /** Unrecognized Skills */
            unrecognized_skills: string[];
            /** Soft Skills */
            soft_skills: string[];
            /** Education */
            education: components["schemas"]["Education"][];
            highest_education: components["schemas"]["EducationLevel"] | null;
            /** Certifications */
            certifications: string[];
        };
        /** Role */
        Role: {
            /**
             * Title
             * @description Job title exactly as written, e.g. 'Software Engineer II'
             */
            title: string;
            /** Company */
            company?: string | null;
            /**
             * Start
             * @description 'YYYY-MM' or 'YYYY'; null if not stated
             */
            start?: string | null;
            /**
             * End
             * @description 'YYYY-MM', 'YYYY', or 'present' for a current role; null if unknown
             */
            end?: string | null;
            /**
             * Is Internship
             * @description True for internships, trainee or apprentice positions
             */
            is_internship: boolean;
        };
        /** ScanCreated */
        ScanCreated: {
            /** Id */
            id: string;
            status: components["schemas"]["ScanStatus"];
            stage: components["schemas"]["ScanStage"];
            /** Progress */
            progress: number;
            /** Error */
            error?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Events Url */
            events_url: string;
            /** Result Url */
            result_url: string;
        };
        /**
         * ScanResult
         * @description The full report. Score fields are null until the scan has finished.
         */
        ScanResult: {
            /** Id */
            id: string;
            status: components["schemas"]["ScanStatus"];
            stage: components["schemas"]["ScanStage"];
            /** Progress */
            progress: number;
            /** Error */
            error?: string | null;
            /** Error Code */
            error_code?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at: string | null;
            resume_file: components["schemas"]["FileSummary"];
            jd_file: components["schemas"]["FileSummary"] | null;
            ats: components["schemas"]["ATSScore"] | null;
            suggestions: components["schemas"]["Suggestions"] | null;
            format_report: components["schemas"]["FormatReport"] | null;
            profile: components["schemas"]["ResumeProfile"] | null;
            requirements: components["schemas"]["JobRequirements"] | null;
            /** Timings Ms */
            timings_ms: {
                [key: string]: number;
            };
        };
        /**
         * ScanStage
         * @description Pipeline stage, streamed to the frontend as progress.
         * @enum {string}
         */
        ScanStage: "uploaded" | "parsing" | "extracting" | "scoring" | "suggesting" | "done";
        /**
         * ScanStatus
         * @enum {string}
         */
        ScanStatus: "queued" | "processing" | "completed" | "partial" | "failed";
        /** ScoreResponse */
        ScoreResponse: {
            resume_file: components["schemas"]["UploadInfo"];
            jd_file: components["schemas"]["UploadInfo"] | null;
            ats: components["schemas"]["ATSScore"];
            profile: components["schemas"]["ResumeProfile"];
            requirements: components["schemas"]["JobRequirements"];
        };
        /** Section */
        Section: {
            /** Key */
            key: string;
            /** Heading */
            heading?: string | null;
            /**
             * Content
             * @default
             */
            content: string;
        };
        /**
         * Seniority
         * @enum {string}
         */
        Seniority: "intern" | "entry" | "mid" | "senior" | "lead" | "principal" | "unspecified";
        /**
         * Severity
         * @enum {string}
         */
        Severity: "critical" | "warning" | "info";
        /** SkillMatch */
        SkillMatch: {
            /** Requirement */
            requirement: string;
            /** Required */
            required: boolean;
            /** Matched */
            matched: boolean;
            /** Matched With */
            matched_with?: string | null;
            /** Source */
            source?: ("skills" | "text") | null;
        };
        /**
         * SkillRequirement
         * @description One JD skill requirement, satisfied by any of its (canonical) options.
         */
        SkillRequirement: {
            /** Any Of */
            any_of: string[];
        };
        /** Suggestion */
        Suggestion: {
            category: components["schemas"]["SuggestionCategory"];
            priority: components["schemas"]["Priority"];
            /**
             * Title
             * @description Short action, at most 10 words, e.g. 'Show your AWS work'
             */
            title: string;
            /**
             * Detail
             * @description One to three sentences: what to change and why it helps
             */
            detail: string;
            /**
             * Example
             * @description Optional rewritten resume line that rephrases facts already in the resume; never adds new facts
             */
            example?: string | null;
        };
        /**
         * SuggestionCategory
         * @enum {string}
         */
        SuggestionCategory: "skills" | "experience" | "impact" | "formatting" | "summary" | "other";
        /** Suggestions */
        Suggestions: {
            /**
             * Overview
             * @description Two or three sentences summarising the fit
             */
            overview: string;
            /**
             * Suggestions
             * @description At most 8, most impactful first
             */
            suggestions: components["schemas"]["Suggestion"][];
        };
        /** UploadInfo */
        UploadInfo: {
            /** Filename */
            filename: string | null;
            /** Size Bytes */
            size_bytes: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readiness_api_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    create_scan_api_scans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_scan_api_scans_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_api_scans__scan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scan_api_scans__scan_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_events_api_scans__scan_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_resume_api_parse_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_parse_resume_api_parse_resume_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeParseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_job_description_api_parse_job_description_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_parse_job_description_api_parse_job_description_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDescriptionParseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_resume_profile_api_extract_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_resume_profile_api_extract_resume_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeExtractResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_job_requirements_api_extract_job_description_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_job_requirements_api_extract_job_description_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDescriptionExtractResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_resume_api_score_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_score_resume_api_score_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
